baseURL = "https://henrybear327.github.io/CodingNotes/"
languageCode = "en-us"
DefaultContentLanguage = "en"

title = "Docdock"
theme = "docdock"
# themesdir = "../.."

publishDir = "docs"

[params]
editURL = "https://github.com/henrybear327/CodingNotes/tree/master/content/"
noHomeIcon = true # default is false
noSearch = false # default is false
showVisitedLinks = true # default is false
# themeStyle = "theme" # overide base css
themeVariant = "" # choose theme variant "green", "gold" , "gray", "blue" (default)
ordersectionsby = "weight" # ordersectionsby = "title"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[[menu.shortcuts]]
pre = "<h3>索引</h3>" # note the pre param which allows you to insert HTML code and used here to separate content’s menu from this “static” menu
name = "<i class='fa fa-link'></i> Tags"
identifier = "Tags"
url = "/tags"
weight = 100

[[menu.shortcuts]]
name = "<i class='fa fa-link'></i> Categories"
identifier = "Categories"
url = "/categories"
weight = 101

[[menu.shortcuts]]
pre = "<h3>About me</h3>" # note the pre param which allows you to insert HTML code and used here to separate content’s menu from this “static” menu
name = "<i class='fa fa-github'></i> Github repo"
identifier = "Henrybear327 Github"
url = "https://github.com/henrybear327?tab=repositories"
weight = 500

[[menu.shortcuts]]
name = "<i class='fa fa-camera'></i> CCULife"
url = "https://itunes.apple.com/tw/app/cculife/id1091437125?l=zh&mt=8"
weight = 501

[[menu.shortcuts]]
name = "<i class='fa fa-bookmark'></i> Hugo Official Site"
identifier = "hugodoc"
url = "https://gohugo.io/"
weight = 502

[[menu.shortcuts]]
pre = "<h3>題解網站</h3>"
name = "<i class='fa fa-bullhorn'></i> amoshyc 題解網站"
url = "https://amoshyc.github.io/CPsolution/"
weight = 1000